import * as T from './three.module.js';
import {Game} from './game.js';
import {stats,clamp,getDifficulty,canPlayDifficulty} from './model.js';
import {SURVIVAL_MAPS,survivalLayout,survivalTerrain,survivalPlayable} from './survival-maps.js';
import {createSurvivalLoadout,createSurvivalInventory,getSurvivalItem,applySurvivalItem,previewSurvivalItem,beginWptUse,completeWptUse,applySurvivalDamage,survivalItemAt} from './survival-items.js';
import {buildSurvivalScene,makeSurvivalSoldier} from './survival-scene.js';
import {updateSurvivalAI} from './survival-ai.js';
import {getSurvivalDifficulty,shuffledSpawnIndices} from './survival-rules.js';
import {objectiveMarkers} from './objective-markers.js';

const phases=[{wait:65,shrink:60,r:430},{wait:45,shrink:55,r:290},{wait:40,shrink:55,r:170},{wait:30,shrink:50,r:85},{wait:25,shrink:45,r:28},{wait:15,shrink:35,r:0}];
export function survivalZone(elapsed,map='tidal'){
 const final=['urban','metro'].includes(map)?{x:0,z:0}:map==='uplink'?{x:20,z:0}:{x:-15,z:-35};let x=0,z=0,radius=720,start=0;
 for(let i=0;i<phases.length;i++){const phase=phases[i],nx=final.x*(i+1)/phases.length,nz=final.z*(i+1)/phases.length,end=start+phase.wait+phase.shrink;if(elapsed<end){const shrinking=elapsed>=start+phase.wait,t=clamp((elapsed-start-phase.wait)/phase.shrink,0,1);return {x:x+(nx-x)*t,z:z+(nz-z)*t,radius:radius+(phase.r-radius)*t,nextX:nx,nextZ:nz,nextRadius:phase.r,phase:i+1,shrinking,remaining:Math.max(0,(shrinking?end:start+phase.wait)-elapsed),endsAt:end,damage:2+i*1.8};}x=nx;z=nz;radius=phase.r;start=end;}
 return {...final,radius:0,nextX:final.x,nextZ:final.z,nextRadius:0,phase:6,shrinking:true,remaining:0,endsAt:start,damage:16+Math.max(0,elapsed-start)*2};
}

export class SurvivalGame extends Game {
 get showEnemyMarkers(){return false;}
 buildMap(id){buildSurvivalScene(this,SURVIVAL_MAPS.some(m=>m.id===id)?id:'tidal');this.zone=survivalZone(0,this.map);this.inventory=createSurvivalInventory();this.shield=0;this.loadouts=[createSurvivalLoadout()];this.slot=0;this.message='';this.messageUntil=0;this.eliminations=[];this.spawnLoot();this.emit();}
 ground(x,z){return survivalTerrain(this.map,x,z);}
 menuCamera(now){const coast=this.map==='tidal',t=now*.000012,x=(coast?-280:280)+Math.sin(t)*22,z=coast?180:200;this.camera.position.set(x,this.ground(x,z)+85,z);this.camera.lookAt(coast?-40:20,25,coast?-100:-70);}
 blocked(x,z,r=.42,feet=null){if(!survivalPlayable(this.map,x,z,r+2))return true;const floor=feet??this.ground(x,z);return this.blocks.some(b=>Math.abs(x-b.x)<b.w+r&&Math.abs(z-b.z)<b.d+r&&floor<b.top-.04&&(!b.overhead||floor+1.8>b.bottom));}
 move(p,dx,dz,r=.42){const lim=this.layout.halfSize-3,nx=clamp(p.x+dx,-lim,lim),nz=clamp(p.z+dz,-lim,lim),feet=p===this.player?p.y-(this.eyeHeight||1.72):null;const rise=(x,z,d)=>this.ground(x,z)-Math.max(this.ground(p.x,p.z),feet??-Infinity)<=Math.abs(d)*1.05+.02;if(!this.blocked(nx,nz,r,feet)&&rise(nx,nz,Math.hypot(dx,dz))){p.x=nx;p.z=nz;return;}if(!this.blocked(nx,p.z,r,feet)&&rise(nx,p.z,dx))p.x=nx;if(!this.blocked(p.x,nz,r,feet)&&rise(p.x,nz,dz))p.z=nz;}
 start(_loadouts,difficultyId='bachelor',options={}){
  if(!canPlayDifficulty(difficultyId,this.cleared))return false;
  const map=SURVIVAL_MAPS.some(m=>m.id===options.mapId)?options.mapId:this.map;
  this.buildMap(map);this.difficulty=getSurvivalDifficulty(difficultyId);this.matchId=crypto.randomUUID();this.result=null;this.time=0;this.remaining=1e9;this.slot=0;this.hp=100;this.shield=0;this.energy=100;this.inventory=createSurvivalInventory();this.loadouts=[createSurvivalLoadout()];this.kills=0;this.deaths=0;this.headshots=0;this.headshotKills=0;this.headshotFlash=0;this.killHeadshot=false;this.blue=0;this.red=0;this.dead=0;this.heat=0;this.overheat=false;this.reload=0;this.reloadTotal=0;this.scanCooldown=0;this.scan=0;this.lastHit=-10;this.eyeHeight=1.72;this.velocityY=0;this.resetKeys();this.touchMove={x:0,y:0};this.fire=false;this.aim=false;this.autoRun=false;this.wptHeld=false;this.wptActive=false;this.wptProgress=0;this.hitFlash=0;this.damageFlash=0;this.killNotice=0;this.nextPulseAt=0;this.stepAt=0;this.shotCount=0;this.resetCombatEffects();this.consume=null;this.eliminations=[];this.zone=survivalZone(0,this.map);this.message='部品を回収してアレイを構築。最後の1人まで生き残れ。';this.messageUntil=8;this.dronesEnabled=false;
  this.lastSpawnByMap??=new Map();this.matchSpawnIndices=Object.freeze(shuffledSpawnIndices(this.layout.spawns.length,this.lastSpawnByMap.get(this.map)));this.playerSpawnIndex=this.matchSpawnIndices[0];this.lastSpawnByMap.set(this.map,this.playerSpawnIndex);
  const p=this.layout.spawns[this.playerSpawnIndex];this.player.set(p[0],this.ground(...p)+1.72,p[1]);const first=this.loot.find(l=>l.spawnIndex===this.playerSpawnIndex&&l.starter==='module');this.yaw=first?Math.atan2(p[0]-first.x,p[1]-first.z):0;this.pitch=first?-.12:0;
  for(let i=0;i<50;i++){const spawnIndex=this.matchSpawnIndices[i+1],p=this.layout.spawns[spawnIndex],e=makeSurvivalSoldier(this,p[0],p[1],i);e.spawnIndex=spawnIndex;e.setup=createSurvivalLoadout(i);e.inventory=createSurvivalInventory();e.lastHit=-10;this.enemies.push(e);}
  this.buildSurvivalNavigation();this.mode='playing';this.zoneWall.visible=true;this.resetMouseInput();this.weapon.visible=true;this.initAudio();this.lock();this.emit();return true;
 }
 trainingReport(){return null;}
 recordWeaponUse(){}
 setSlot(){}
 applyWeaponDamage(e,amount){const hit=applySurvivalDamage(e,amount);e.hp=hit.hp;e.shield=hit.shield;e.lastHit=this.time;e.consume=null;return hit.healthDamage+hit.armorDamage;}
 damageSurvivor(target,amount,source=null,storm=false){if(this.mode!=='playing')return;const actor=target||this;if(actor.dead||actor.hp<=0)return;const hit=applySurvivalDamage(actor,amount,{bypassShield:storm});actor.hp=hit.hp;actor.shield=hit.shield;actor.lastHit=this.time;actor.consume=null;if(!target){this.damageFlash=.3;this.shake=Math.min(1,(this.shake||0)+.5);if(hit.dead){this.hp=0;this.dead=1;this.deaths=1;const count=this.enemies.filter(e=>!e.dead).length;this.finish(storm&&count===0?'draw':'defeat',count===0?1:count+1,storm&&count===0?'給電圏消失で最後の生存者が同時に脱落':storm?'給電圏外で電力を喪失':'他の生存者に撃破された');}}else if(hit.dead)this.kill(target,source===this,false,source,storm);}
 kill(e,player,headshot=false,source=null,storm=false){if(e.dead)return;e.dead=1;e.hp=0;e.consume=null;e.g.visible=false;e.aiTarget=null;if(player){this.kills++;this.killNotice=2.1;this.killHeadshot=headshot;if(headshot)this.headshotKills++;this.sound(750,.07,.09);}this.eliminations.unshift({id:`${this.time}-${e.index}`,text:`${player?'YOU':source?`ARRAY ${String(source.index+1).padStart(2,'0')}`:storm?'給電圏外':'交戦'}  ›  ARRAY ${String(e.index+1).padStart(2,'0')}`,time:this.time});this.eliminations=this.eliminations.slice(0,5);const drop=getSurvivalItem('wpt-shield');this.addLoot({x:e.g.position.x+1,z:e.g.position.z,id:`drop-${e.index}`},drop);}
 finish(outcome,placement,reason='最後の生存者になった'){if(this.mode!=='playing')return;this.result=Object.freeze({gameMode:'survival',matchId:this.matchId,mapId:this.map,difficultyId:this.difficulty.id,playerSpawnIndex:this.playerSpawnIndex,outcome,placement,elapsed:this.time,kills:this.kills,headshotKills:this.headshotKills,reason});this.mode='result';this.releaseFire();this.consume=null;this.wptHeld=false;this.wptActive=false;this.resetCombatEffects();this.resetMouseInput();if(typeof document!=='undefined'&&document.pointerLockElement)document.exitPointerLock();this.emit();}
 handleKeyDown(e){super.handleKeyDown(e);if(this.mode!=='playing'||e.repeat)return;if(e.code==='KeyZ'){this.autoRun=!this.autoRun;this.keys.KeyW=this.autoRun;}if(e.code==='KeyS'&&this.autoRun)this.keys.KeyW=false;if(e.code==='KeyW'||e.code==='KeyS')this.autoRun=false;if(e.code==='KeyF')this.pickup();if(e.code==='KeyH')this.useCell('heal');if(e.code==='KeyJ')this.useCell('shield');if(e.code==='KeyM'||e.code==='Tab'){e.preventDefault();this.mapOpen=!this.mapOpen;this.emit();}}
 pause(){this.consume=null;this.autoRun=false;this.mapOpen=false;super.pause();}
 spawnLoot(){this.loot=[];this.lootCapacity=this.layout.loot.length+150;const body=new T.InstancedMesh(new T.BoxGeometry(.82,.32,.55),new T.MeshStandardMaterial({color:'#273e42',metalness:.6,roughness:.4}),this.lootCapacity),light=new T.InstancedMesh(new T.BoxGeometry(.72,.04,.44),new T.MeshBasicMaterial({color:'#ffffff'}),this.lootCapacity),shaft=new T.InstancedMesh(new T.CylinderGeometry(.035,.07,1.4,5),new T.MeshBasicMaterial({color:'#ffffff',transparent:true,opacity:.65}),this.lootCapacity);for(const m of [body,light,shaft]){m.count=0;m.frustumCulled=false;this.world.add(m);}const patchGeometry=new T.BufferGeometry(),positions=[],normals=[];for(let a=0;a<4;a++)for(let b=0;b<3;b++){const geo=new T.BoxGeometry(.12,.035,.1).translate((a-1.5)*.18,0,(b-1)*.15).toNonIndexed();positions.push(...geo.attributes.position.array);normals.push(...geo.attributes.normal.array);geo.dispose();}patchGeometry.setAttribute('position',new T.Float32BufferAttribute(positions,3));patchGeometry.setAttribute('normal',new T.Float32BufferAttribute(normals,3));const patches=new T.InstancedMesh(patchGeometry,new T.MeshStandardMaterial({color:'#d0bd85',metalness:.7,roughness:.32}),this.lootCapacity),coil=new T.InstancedMesh(new T.TorusGeometry(.26,.05,8,20).rotateX(-Math.PI/2),new T.MeshStandardMaterial({color:'#a2e4d4',emissive:'#285a53',metalness:.6,roughness:.28}),this.lootCapacity);for(const m of [patches,coil]){m.count=0;m.frustumCulled=false;this.world.add(m);}this.lootMeshes={body,light,shaft,patches,coil};for(const [i,p] of this.layout.loot.entries()){const item=p.starter==='module'?getSurvivalItem('array-64'):p.starter==='wpt'?getSurvivalItem('wpt-shield'):survivalItemAt(this.layout.seed,i,p.category);let point=p;if(p.starter){const spawn=this.layout.spawns[p.spawnIndex],poi=this.layout.pois.reduce((a,b)=>Math.hypot(spawn[0]-a.x,spawn[1]-a.z)<Math.hypot(spawn[0]-b.x,spawn[1]-b.z)?a:b),angle=Math.atan2(poi.z-spawn[1],poi.x-spawn[0])+(p.starter==='wpt'?.25:0),d=p.starter==='wpt'?11:8,nx=spawn[0]+Math.cos(angle)*d,nz=spawn[1]+Math.sin(angle)*d;if(!this.blocked(nx,nz,.6)&&this.walkableSegment(spawn[0],spawn[1],nx,nz,.6))point={...p,x:nx,z:nz};}this.addLoot(point,item);} }
 addLoot(point,item){if(this.loot.length>=this.lootCapacity)return;let x=point.x,z=point.z;if(this.blocked(x,z,.6)){let found=false;for(let k=0;k<24;k++){const a=k*2.4,r=2+k*.3,nx=x+Math.cos(a)*r,nz=z+Math.sin(a)*r;if(!this.blocked(nx,nz,.6)){x=nx;z=nz;found=true;break;}}if(!found)return;}const i=this.loot.length,l={...point,x,z,y:this.ground(x,z),itemId:item.id,available:true,index:i};this.loot.push(l);const matrix=new T.Object3D();for(const [key,m] of Object.entries(this.lootMeshes)){matrix.position.set(x,l.y+(key==='body'?.2:key==='light'?.385:key==='shaft'?.85:.44),z);const hidden=key==='patches'&&item.kind==='consumable'||key==='coil'&&item.kind!=='consumable';matrix.scale.set(hidden?0:1,hidden?0:key==='shaft'?.55:1,hidden?0:1);matrix.updateMatrix();m.setMatrixAt(i,matrix.matrix);if(key!=='body')m.setColorAt(i,new T.Color(item.color));m.count=this.loot.length;m.instanceMatrix.needsUpdate=true;if(m.instanceColor)m.instanceColor.needsUpdate=true;}return l;}
 removeLoot(l){l.available=false;const m=new T.Matrix4().makeScale(0,0,0);for(const mesh of Object.values(this.lootMeshes)){mesh.setMatrixAt(l.index,m);mesh.instanceMatrix.needsUpdate=true;}}
 nearbyLoot(actor=null,max=3.2){const p=actor?actor.g.position:this.player;return this.loot.filter(l=>l.available&&Math.hypot(l.x-p.x,l.z-p.z)<=max&&Math.abs(l.y-(actor?p.y:p.y-(this.eyeHeight||1.72)))<2).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z)).find(l=>this.line((actor?this.actorPoint(actor):p),new T.Vector3(l.x,l.y+.45,l.z)))||null;}
 pickup(){if(this.mode!=='playing'||this.dead)return;const l=this.nearbyLoot();if(!l)return;const r=applySurvivalItem(this.loadouts[0],this.inventory,l.itemId);this.message=r.ok?`${r.item.name} · ${r.reason}`:r.reason;this.messageUntil=this.time+4;if(r.ok){this.loadouts=[r.setup];this.inventory=r.inventory;this.consume=null;this.removeLoot(l);this.sound(650,.09,.07);}this.emit();}
 seekLoot(e){const nearby=this.nearbyLoot(e,2.8);if(nearby){const item=getSurvivalItem(nearby.itemId),r=applySurvivalItem(e.setup,e.inventory,item.id),before=stats(e.setup),after=stats(r.setup);const desirable=item.kind==='consumable'||(after.range+after.sustainedDps*1.4+after.moveSpeed*5)>=(before.range+before.sustainedDps*1.4+before.moveSpeed*5)*.94;if(r.ok&&desirable){e.setup=r.setup;e.inventory=r.inventory;this.removeLoot(nearby);}else e.ignoredLoot=nearby.id;}
  return this.loot.filter(l=>l.available&&l.id!==e.ignoredLoot&&Math.hypot(l.x-e.g.position.x,l.z-e.g.position.z)<90&&Math.hypot(l.x-(this.zone.shrinking?this.zone.nextX:this.zone.x),l.z-(this.zone.shrinking?this.zone.nextZ:this.zone.z))<Math.max(this.zone.shrinking?this.zone.nextRadius:this.zone.radius,40)).sort((a,b)=>Math.hypot(a.x-e.g.position.x,a.z-e.g.position.z)-Math.hypot(b.x-e.g.position.x,b.z-e.g.position.z))[0]||null;
 }
 useCell(resource){if(this.mode!=='playing'||this.dead)return;const action=beginWptUse(this,this.inventory,resource);if(!action.ok){this.message=action.reason;this.messageUntil=this.time+3;this.emit();return;}if(this.consume)return;this.consume={...action,elapsed:0,start:this.player.clone(),lastHit:this.lastHit};this.releaseFire();this.emit();}
 updateWPT(dt){this.wptActive=false;this.wptState={status:'inactive',label:'WPT',distance:0,progress:0};if(this.dead||this.mode!=='playing')return;
  if(this.consume){const a=this.consume;if(this.moving||this.isFiring()||this.reload>0||this.lastHit>a.lastHit||this.player.distanceTo(a.start)>.12){this.consume=null;this.message='WPT給電を中断 · セルは保持';this.messageUntil=this.time+2;return;}a.elapsed+=dt;this.wptActive=true;if(a.elapsed>=a.duration){const r=completeWptUse(this,this.inventory,a.resource);if(r.ok){this.hp=r.vitals.hp;this.shield=r.vitals.shield;this.inventory=r.inventory;}this.consume=null;this.sound(820,.15,.1);}return;}
  const p=this.player,station=this.stations.reduce((best,s)=>!best||Math.hypot(p.x-s.x,p.z-s.z)<Math.hypot(p.x-best.x,p.z-best.z)?s:best,null);if(!station)return;const d=Math.hypot(p.x-station.x,p.z-station.z);if(d>station.radius){this.wptProgress=0;return;}let status=this.enemies.some(e=>!e.dead&&Math.hypot(e.g.position.x-station.x,e.g.position.z-station.z)<10)?'contested':this.time-this.lastHit<2?'under-fire':this.moving||Math.abs(p.y-this.ground(p.x,p.z)-(this.eyeHeight||1.72))>.15?'moving':this.isFiring()||this.reload>0?'busy':!this.line(station.emitter,p)?'blocked':this.shield>=100&&this.energy>=100?'complete':'ready';
  if(status==='ready'&&(this.keys.KeyE||this.wptHeld)){this.wptProgress+=dt;status=this.wptProgress<.8?'linking':'charging';if(status==='charging'){this.shield=Math.min(100,this.shield+12*dt);this.energy=Math.min(100,this.energy+24*dt);this.wptActive=true;}if(this.time-(this.wptBeamAt||-100)>.15){this.wptBeamAt=this.time;this.beam(station.emitter,p,'#91e4e3',.04);}}else this.wptProgress=0;this.wptState={status,label:'WPT給電所',distance:Math.round(d),progress:Math.min(1,this.wptProgress/.8)};
 }
 fireWeapon(dt){if(this.consume)return false;return super.fireWeapon(dt);}
 updateAI(e,dt){if(e.dead||this.mode!=='playing')return;if(e.consume){if(e.lastHit>e.consume.lastHit){e.consume=null;}else{e.consume.elapsed+=dt;if(e.consume.elapsed>=e.consume.duration){const r=completeWptUse(e,e.inventory,e.consume.resource);if(r.ok){e.hp=r.vitals.hp;e.shield=r.vitals.shield;e.inventory=r.inventory;}e.consume=null;}return;}}
  if(!e.aiHasTarget&&this.time-e.lastHit>3&&Math.hypot(e.g.position.x-this.zone.x,e.g.position.z-this.zone.z)<this.zone.radius-12){const kind=e.hp<65?'heal':e.shield<60?'shield':null;if(kind){const a=beginWptUse(e,e.inventory,kind);if(a.ok){e.consume={...a,elapsed:0,lastHit:e.lastHit};return;}}}
  updateSurvivalAI(this,e,dt);
 }
 update(dt){if(this.mode!=='playing')return;if(this.autoRun)this.keys.KeyW=true;this.zone=survivalZone(this.time+dt,this.map);this.remaining=1e9;super.update(dt);if(this.mode!=='playing')return;
  const zone=this.zone;this.zoneWall.position.set(zone.x,80,zone.z);this.zoneWall.scale.set(Math.max(.1,zone.radius),1,Math.max(.1,zone.radius));this.zoneWall.material.uniforms.clock.value=this.time;
  for(const e of this.enemies){if(e.dead)continue;if(Math.hypot(e.g.position.x-zone.x,e.g.position.z-zone.z)>zone.radius)this.damageSurvivor(e,zone.damage*dt,null,true);const close=e.g.position.distanceToSquared(this.player)<110*110;for(const part of e.g.children)part.castShadow=close;}
  if(Math.hypot(this.player.x-zone.x,this.player.z-zone.z)>zone.radius)this.damageSurvivor(null,zone.damage*dt,null,true);
  if(this.mode==='playing'&&!this.enemies.some(e=>!e.dead))this.finish('victory',1);
  if(this.survivalSun){const p=this.player;this.survivalSun.position.set(p.x-260,p.y+300,p.z-170);this.survivalSun.target.position.copy(p);}
 }
 groundIntersection(a,b){const dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z,len=Math.hypot(dx,dy,dz),steps=Math.max(1,Math.ceil(len/1.6));let prev=0;for(let i=1;i<=steps;i++){const t=i/steps,x=a.x+dx*t,y=a.y+dy*t,z=a.z+dz*t;if(y<this.ground(x,z)){let lo=prev,hi=t;for(let n=0;n<6;n++){const m=(lo+hi)/2;if(a.y+dy*m<this.ground(a.x+dx*m,a.z+dz*m))hi=m;else lo=m;}return new T.Vector3(a.x+dx*hi,a.y+dy*hi,a.z+dz*hi);}prev=t;}return null;}
 buildSurvivalNavigation(){const step=12,origin=-504,size=85,nodes=Array.from({length:size*size},(_,i)=>({x:origin+i%size*step,z:origin+Math.floor(i/size)*step,links:[]}));for(const n of nodes)n.open=!this.blocked(n.x,n.z,.75);for(let i=0;i<nodes.length;i++){const n=nodes[i];if(!n.open)continue;for(const [dx,dz] of [[1,0],[0,1],[1,1],[-1,1]]){const ix=i%size+dx,iz=Math.floor(i/size)+dz;if(ix<0||iz<0||ix>=size||iz>=size)continue;const j=iz*size+ix,m=nodes[j];if(m.open&&this.walkableSegment(n.x,n.z,m.x,m.z,.65)){n.links.push(j);m.links.push(i);}}}this.survivalNav={nodes,step,origin,size,fields:new Map()};}
 navIndex(x,z){const nav=this.survivalNav,ix=clamp(Math.round((x-nav.origin)/nav.step),0,nav.size-1),iz=clamp(Math.round((z-nav.origin)/nav.step),0,nav.size-1);let best=-1,dist=Infinity;for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++){const nx=ix+dx,nz=iz+dz;if(nx<0||nz<0||nx>=nav.size||nz>=nav.size)continue;const i=nz*nav.size+nx,n=nav.nodes[i],d=Math.hypot(n.x-x,n.z-z);if(n.open&&d<dist&&this.walkableSegment(x,z,n.x,n.z,.55)){dist=d;best=i;}}return best;}
 survivalNavigationTarget(e,goal){if(!this.survivalNav)return goal;const p=e.g.position;if(this.time<(e.routeAt||0)&&e.routeGoal&&Math.hypot(goal.x-e.routeGoal.x,goal.z-e.routeGoal.z)<20&&e.routePoint&&Math.hypot(p.x-e.routePoint.x,p.z-e.routePoint.z)>2)return e.routePoint;e.routeAt=this.time+1.5;e.routeGoal={x:goal.x,z:goal.z};if(this.walkableSegment(p.x,p.z,goal.x,goal.z,.55)){e.routePoint=goal;return goal;}const start=this.navIndex(p.x,p.z),end=this.navIndex(goal.x,goal.z),nav=this.survivalNav;if(start<0||end<0)return goal;let field=nav.fields.get(end);if(!field){field=new Int16Array(nav.nodes.length).fill(-1);const queue=new Int32Array(nav.nodes.length);let h=0,t=1;queue[0]=end;field[end]=0;while(h<t){const i=queue[h++];for(const j of nav.nodes[i].links)if(field[j]<0){field[j]=field[i]+1;queue[t++]=j;}}if(nav.fields.size>64)nav.fields.clear();nav.fields.set(end,field);}let best=start;for(const j of nav.nodes[start].links)if(field[j]>=0&&(field[best]<0||field[j]<field[best]))best=j;e.routePoint=nav.nodes[best];return e.routePoint;}
 hudExtras(){const s=this.loadouts?.[0]||createSurvivalLoadout(),z=this.zone||survivalZone(0,this.map),p=this.player,loot=this.mode==='playing'?this.nearbyLoot():null,item=loot?getSurvivalItem(loot.itemId):null,preview=item?previewSurvivalItem(s,this.inventory,item.id,stats):null,nearest=this.loot?.filter(l=>l.available&&Math.hypot(l.x-p.x,l.z-p.z)<55).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z)).slice(0,3)||[],markers=objectiveMarkers(this.camera,p,nearest.map((l,i)=>({id:l.id,x:l.x,y:l.y-4.6,z:l.z,owner:'neutral'})),typeof innerWidth==='number'?innerWidth:1280,typeof innerHeight==='number'?innerHeight:720);return {gameMode:'survival',activeSetup:{...s},shield:Math.ceil(this.shield||0),inventory:{...this.inventory},remainingAlive:this.enemies.filter(e=>!e.dead).length+(this.dead?0:1),elapsed:this.time,zone:z,zoneOutside:Math.hypot(p.x-z.x,p.z-z.z)>z.radius,zoneDistance:Math.ceil(Math.max(0,Math.hypot(p.x-z.nextX,p.z-z.nextZ)-z.nextRadius)),mapOpen:!!this.mapOpen,consume:this.consume?{resource:this.consume.resource,elapsed:this.consume.elapsed,duration:this.consume.duration}:null,loot:item?{...item,id:loot.id,ok:preview.ok,reason:preview.reason,before:preview.before,after:preview.after}:null,lootMarkers:markers.map(m=>({...m,label:getSurvivalItem(nearest.find(l=>l.id===m.id).itemId).name,color:getSurvivalItem(nearest.find(l=>l.id===m.id).itemId).color})),message:this.time<(this.messageUntil||0)?this.message:'',eliminations:(this.eliminations||[]).filter(k=>this.time-k.time<9),trainingReport:null,weaponXP:0,objectiveMarkers:[]};}
}
