import assert from 'node:assert/strict';
import * as T from '../engine/three.module.js';
import {objectiveMarkers} from '../engine/objective-markers.js';
import {MAPS,layoutFor,terrain} from '../engine/maps.js';
let passed=0,failed=0;
function test(name,fn){try{fn();passed++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+'\n'+e.message);}}
function camera(w=1280,h=720,fov=72){const c=new T.PerspectiveCamera(fov,w/h,.06,650);c.position.set(0,6,0);c.rotation.order='YXZ';return c;}
function objective(x,y,z,id='A'){return {id,x,y,z,owner:'neutral',progress:0};}
function finite(ms,w,h){for(const m of ms){for(const k of ['x','y','angle','distance','anchorOffset'])assert.ok(Number.isFinite(m[k]),`${m.id}.${k}=${m[k]}`);assert.ok(m.x>=0&&m.x<=100&&m.y>=0&&m.y<=100);assert.ok(m.distance>=0);}}
function separated(ms,w,h){for(let i=0;i<ms.length;i++)for(let j=i+1;j<ms.length;j++){const a=ms[i],b=ms[j],dx=Math.abs(a.x-b.x)*w/100,dy=Math.abs(a.y-b.y)*h/100;assert.ok(dx>=106||dy>=50,`${a.id}/${b.id} overlap at ${w}×${h}: dx=${dx}, dy=${dy}`);}}
test('front marker matches camera projection; ground distance ignores anchor lift',()=>{const c=camera();const [m]=objectiveMarkers(c,c.position,[objective(10,0,-50)]);const p=new T.Vector3(10,6,-50).project(c);assert.equal(m.behind,false);assert.equal(m.offscreen,false);assert.ok(Math.abs(m.x-(p.x+1)*50)<1e-9);assert.ok(Math.abs(m.y-(1-p.y)*50)<1e-9);assert.equal(m.distance,51);});
test('behind markers use shortest horizontal turn and deterministic exact-rear direction',()=>{for(const [x,expected] of [[-10,180],[10,0],[0,0]]){const c=camera();const [m]=objectiveMarkers(c,c.position,[objective(x,0,20)]);assert.equal(m.behind,true);assert.equal(m.offscreen,true);assert.equal(m.angle,expected);assert.equal(m.x<50,x<0);}});
test('offscreen arrow bearing is measured in screen pixels across aspect ratios',()=>{for(const [w,h] of [[1280,720],[375,667],[568,320]]){const c=camera(w,h);const [m]=objectiveMarkers(c,c.position,[objective(10,10,-5)],w,h);assert.equal(m.offscreen,true);assert.equal(m.behind,false);assert.ok(Math.abs(m.angle+45)<1e-8,`${w}×${h}: expected −45°, got ${m.angle}°`);}});
test('near plane, exact camera location, high/low targets stay finite',()=>{for(const z of [-.06,-.001,0,.001,.06])for(const y of [-100,0,6,100]){const c=camera();const ms=objectiveMarkers(c,c.position,[objective(0,y,z)]);finite(ms);}});
test('same-bearing rear markers remain distinct in desktop and mobile landscapes',()=>{for(const [w,h] of [[1280,720],[375,667],[667,375],[568,320]]){const c=camera(w,h);const ms=objectiveMarkers(c,c.position,[10,20,30].map((z,i)=>objective(0,0,z,'ABC'[i])),w,h);separated(ms,w,h);}});
test('same-bearing front markers remain distinct near every vertical boundary',()=>{for(const [w,h] of [[1280,720],[375,667],[667,375],[568,320]])for(const shift of [-.3,-.15,0,.15,.3]){const c=camera(w,h);const ms=objectiveMarkers(c,c.position,[20,40,60].map((d,i)=>objective(0,shift*d,-d,'ABC'[i])),w,h);separated(ms,w,h);}});
test('scope narrowing turns former in-view target into correctly directed edge marker',()=>{const c=camera();const o=objective(20,0,-30);const wide=objectiveMarkers(c,c.position,[o])[0];assert.equal(wide.offscreen,false);c.fov=18;c.updateProjectionMatrix();const scoped=objectiveMarkers(c,c.position,[o])[0];assert.equal(scoped.offscreen,true);assert.ok(scoped.x>50);assert.ok(Math.abs(scoped.angle)<1e-9);});
test('camera yaw and pitch transform labels without stale world matrices',()=>{const c=camera();for(const yaw of [-Math.PI,-Math.PI/2,0,Math.PI/2,Math.PI])for(const pitch of [-1.2,0,1.2]){c.rotation.set(pitch,yaw,0,'YXZ');c.updateMatrixWorld(true);const anchor=new T.Vector3(0,0,-50).applyMatrix4(c.matrixWorld);const o=objective(anchor.x,anchor.y-6,anchor.z);const [m]=objectiveMarkers(c,c.position,[o]);assert.equal(m.behind,false);assert.equal(m.offscreen,false);assert.ok(Math.abs(m.x-50)<1e-8&&Math.abs(m.y-50)<1e-8);}});
test('capture-zone label observes horizontal and vertical reach separately',()=>{const c=camera();const o=objective(0,0,0);assert.equal(objectiveMarkers(c,new T.Vector3(0,1.72,0),[o])[0].inside,true);assert.equal(objectiveMarkers(c,new T.Vector3(0,5,0),[o])[0].inside,false);assert.equal(objectiveMarkers(c,new T.Vector3(6.5,1.72,0),[o])[0].inside,false);});
test('all seven maps: finite three-objective labels over spawn/point positions, scoped FOV and view rotations',()=>{let cases=0;for(const map of MAPS){const l=layoutFor(map.id);const os=l.objectives.map(([x,z],i)=>({...objective(x,terrain(map.id,x,z),z,'ABC'[i]),owner:['blue','neutral','red'][i],progress:[100,0,-100][i]}));for(const [w,h] of [[1280,720],[375,667],[667,375],[568,320]])for(const fov of [72,57.6,28.8,18])for(const [x,z] of [l.spawn,...l.objectives])for(const yaw of [0,Math.PI/2,Math.PI,-Math.PI/2])for(const pitch of [-1.2,0,1.2]){const c=camera(w,h,fov);c.position.set(x,terrain(map.id,x,z)+1.72,z);c.rotation.set(pitch,yaw,0,'YXZ');const ms=objectiveMarkers(c,c.position,os,w,h);assert.equal(ms.length,3);finite(ms,w,h);assert.deepEqual(ms.map(m=>m.owner),['blue','neutral','red']);assert.deepEqual(ms.map(m=>m.id),['A','B','C']);cases++;}}assert.equal(cases,5376);});
console.log(JSON.stringify({passed,failed}));if(failed)process.exitCode=1;
