import assert from 'node:assert/strict';
import * as T from '../engine/three.module.js';
import {Game} from '../engine/game.js';
import {PRESETS,usageXP,validTrainingReport} from '../engine/model.js';
globalThis.document={pointerLockElement:null};
function flat(){const g=Object.create(Game.prototype);Object.assign(g,{mode:'playing',map:'base',trainingMap:'base',matchId:'00000000-0000-4000-8000-000000000099',keys:{},enemies:[],allies:[],fx:[],time:1,slot:0,loadouts:PRESETS.map(s=>({...s})),player:new T.Vector3(0,1.72,0),world:new T.Group(),scene:new T.Scene(),camera:new T.PerspectiveCamera(72,1,.06,650),ray:new T.Raycaster(),sharedGeo:{box:new T.BoxGeometry(1,1,1),cyl:new T.CylinderGeometry(1,1,1,10),sphere:new T.SphereGeometry(1,12,8)},blocks:[],occluders:[],ground:()=>0,energy:100,heat:0,reload:0,overheat:false,dead:0,fire:true,wptHeld:false,kills:0,headshots:0,headshotKills:0,blue:0,yaw:0,pitch:0,beam:()=>{},spark:()=>{},sound:()=>{},gunshot:()=>{},onState:s=>{g.state=s;},objectives:[],scanCooldown:0});g.scene.add(g.world);return g;}
function enemy(g,hp=100,x=0,z=-20){const e=g.makeSoldier('enemy',x,z,0);e.hp=hp;g.enemies.push(e);return e;}
function pulse(g,e,head=false,count=1){const d=e?e.g.position.clone().add(new T.Vector3(0,head?1.87:1.25,0)).sub(g.player).normalize():new T.Vector3(0,0,-1);g.shotDirections=()=>Array.from({length:count},()=>d.clone());g.fire=true;g.energy=100;g.heat=0;g.overheat=false;g.reload=0;g.nextPulseAt=g.time;g.triggerWasHeld=false;g.fireWeapon(1/60);}
let passed=0;function check(name,fn){fn();passed++;console.log('PASS '+name);}
check('Empty fire and fully blocked target award no progress',()=>{const g=flat();pulse(g);assert.equal(g.trainingReport(),null);const e=enemy(g);const wall=g.box(10,3,.5,0,1.5,-10,g.mat('#777777'));g.occluders.push(wall);g.world.updateMatrixWorld(true);g.time+=1;pulse(g,e);assert.equal(e.hp,100);assert.equal(g.trainingReport(),null);});
check('Ordinary hit records actual damage on precisely its source setup',()=>{const g=flat(),e=enemy(g);pulse(g,e);const report=g.trainingReport();assert(validTrainingReport(report));assert.equal(report.weapons.length,1);assert.equal(report.weapons[0].id,'precision');assert(Math.abs(report.weapons[0].damage-(100-e.hp))<.001);assert.equal(report.weapons[0].kills,0);assert.equal(report.weapons[0].headshotKills,0);});
check('Five overlapping beams cannot credit overkill, duplicate kills or damage after death',()=>{const g=flat(),e=enemy(g,.1);pulse(g,e,false,5);let w=g.trainingReport().weapons[0];assert.equal(w.damage,.1);assert.equal(w.kills,1);assert.equal(w.headshotKills,0);assert.equal(usageXP(w),12);g.time+=1;pulse(g,e,false,5);assert.deepEqual(g.trainingReport().weapons[0],w);});
check('Head kill counts once and switching setup keeps each usage total separate',()=>{const g=flat(),a=enemy(g,.1);pulse(g,a,true,5);const b=enemy(g,100,3);g.setSlot(1);g.time+=1;pulse(g,b);const usage=Object.fromEntries(g.trainingReport().weapons.map(w=>[w.id,w]));assert.equal(usage.precision.headshotKills,1);assert.equal(usage.precision.kills,1);assert.equal(usage.precision.damage,.1);assert(usage.sweep.damage>0);assert.equal(usage.sweep.kills,0);assert.equal(usageXP(usage.precision),18);});
check('Reports remain immutable copies and retain original battle map after menu selection changes',()=>{const g=flat(),e=enemy(g);pulse(g,e);const report=g.trainingReport();g.map='river';g.time+=1;pulse(g,e);assert.equal(g.trainingReport().mapId,'base');assert(g.trainingReport().weapons[0].damage>report.weapons[0].damage);assert.equal(report.mapId,'base');});
check('NaN, negative, zero and infinite damage calls cannot poison totals',()=>{const g=flat();for(const damage of [NaN,0,-1,Infinity])g.recordWeaponUse('precision',damage,true,true);assert.equal(g.trainingReport(),null);});
console.log(`${passed} weapon usage engine checks passed`);
