import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import * as rules from '../engine/model.js';
const root=fileURLToPath(new URL('..',import.meta.url)),require=createRequire(root+'/package.json'),ts=require('typescript');
const code=ts.transpileModule(readFileSync(root+'/app/use-weapon-training.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
function harness(storage=new Map()){
 let slots=[],index=0,effects=[],dirty=false,now=100000,nextTimer=0,report=null,mode='menu',value;
 const timers=new Map(),requests=[];
 const equal=(a,b)=>a&&b&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i]));
 const react={useState(init){const i=index++;slots[i]??={value:typeof init==='function'?init():init};return [slots[i].value,v=>{const next=typeof v==='function'?v(slots[i].value):v;if(!Object.is(next,slots[i].value)){slots[i].value=next;dirty=true;}}];},useRef(v){const i=index++;return slots[i]??=( {current:v});},useCallback(fn,deps){const i=index++;if(!slots[i]||!equal(slots[i].deps,deps))slots[i]={fn,deps};return slots[i].fn;},useEffect(fn,deps){const i=index++;if(!slots[i]||!equal(slots[i].deps,deps)){const old=slots[i];slots[i]={deps,cleanup:old?.cleanup};effects.push(()=>{old?.cleanup?.();slots[i].cleanup=fn();});}}};
 const context={exports:{},require:p=>p==='react'?react:p==='./local-storage.js'?{localRequest:(...args)=>context.fetch(...args)}:rules,AbortController,Date:class extends Date{static now(){return now;}},sessionStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setTimeout:(fn,ms)=>{const id=++nextTimer;timers.set(id,{fn,at:now+ms,ms:0});return id;},clearTimeout:id=>timers.delete(id),setInterval:(fn,ms)=>{const id=++nextTimer;timers.set(id,{fn,at:now+ms,ms});return id;},clearInterval:id=>timers.delete(id),fetch:(url,options={})=>new Promise((resolve,reject)=>{const req={url,options,body:options.body&&JSON.parse(options.body),resolve:data=>resolve({ok:true,json:async()=>data}),fail:message=>resolve({ok:false,json:async()=>({error:message})})};requests.push(req);options.signal?.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'})));})};
 vm.runInNewContext(code,context,{filename:'training-hook.cjs'});
 function render(){dirty=false;index=0;value=context.exports.useWeaponTraining(report,mode);const tasks=effects;effects=[];tasks.forEach(fn=>fn());}
 render();
 return {requests,storage,get value(){return value;},async pump(){for(let i=0;i<25;i++){await Promise.resolve();if(dirty)render();}},async input(r,m){report=r;mode=m;render();await this.pump();},async advance(ms){const end=now+ms;while(true){const entry=[...timers.entries()].sort((a,b)=>a[1].at-b[1].at)[0];if(!entry||entry[1].at>end)break;now=entry[1].at;if(entry[1].ms)entry[1].at+=entry[1].ms;else timers.delete(entry[0]);entry[1].fn();await this.pump();}now=end;await this.pump();},unmount(){slots.forEach(s=>s.cleanup?.());}};
}
let n=0;const check=async(name,fn)=>{await fn();n++;console.log('PASS '+name);};
const report=(damage=100,id='precision',match='12345678-1234-1234-1234-123456789abc')=>({matchId:match,mapId:'base',elapsed:20,weapons:[{id,damage,kills:0,headshotKills:0}]});
const ack=(xp=10,ownerKey='a',id='precision')=>({ownerKey,xp:{[id]:xp},receipts:{[id]:xp}});
async function initialized(storage){const h=harness(storage);h.requests[0].resolve({ownerKey:'a',xp:{}});await h.pump();return h;}
await check('Loads account XP, caches cumulative draft before POST',async()=>{const h=await initialized();await h.input(report(),'playing');assert.equal(h.requests.length,2);assert.equal(h.value.pending,1);assert.equal(JSON.parse(h.storage.get('array-front-training-pending:a'))[0].weapons[0].damage,100);h.requests[1].resolve(ack());await h.pump();assert.equal(h.value.xp.precision,10);assert.equal(h.value.pending,0);assert.deepEqual(JSON.parse(h.storage.get('array-front-training-pending:a')),[]);h.unmount();});
await check('Newer cumulative damage survives older inflight acknowledgment',async()=>{const h=await initialized();await h.input(report(),'playing');await h.input(report(200),'playing');h.requests[1].resolve(ack());await h.pump();assert.equal(h.value.pending,1);await h.advance(15000);assert.equal(h.requests.length,3);assert.equal(h.requests[2].body.weapons[0].damage,200);h.requests[2].resolve(ack(20));await h.pump();assert.equal(h.value.xp.precision,20);assert.equal(h.value.pending,0);h.unmount();});
await check('Repeated HUD emissions do not repeat acknowledged XP',async()=>{const h=await initialized();await h.input(report(),'playing');h.requests[1].resolve(ack());await h.pump();for(let i=0;i<5;i++)await h.input(report(),'playing');await h.advance(16000);assert.equal(h.requests.length,2);h.unmount();});
await check('Final result flush bypasses combat throttle',async()=>{const h=await initialized();await h.input(report(),'playing');h.requests[1].resolve(ack());await h.pump();await h.input(report(200),'result');assert.equal(h.requests.length,3);assert.equal(h.requests[2].body.weapons[0].damage,200);h.unmount();});
await check('Failure retains draft and menu retries save it',async()=>{const h=await initialized();await h.input(report(),'playing');h.requests[1].fail('offline');await h.pump();assert.equal(h.value.error,'offline');assert.equal(h.value.pending,1);await h.input(report(),'menu');assert.equal(h.requests.length,3);h.requests[2].resolve(ack());await h.pump();assert.equal(h.value.error,'');assert.equal(h.value.pending,0);h.unmount();});
await check('Session replay sends only matching account drafts',async()=>{const storage=new Map([['array-front-training-pending:a',JSON.stringify([report()])],['array-front-training-pending:b',JSON.stringify([report(999)])]]);const h=await initialized(storage);assert.equal(h.requests.length,2);assert.equal(h.requests[1].body.weapons[0].damage,100);h.unmount();});
await check('Queued previous match survives immediate restart',async()=>{const h=await initialized();await h.input(report(),'result');await h.input(null,'playing');await h.input(report(50,'wide','aaaaaaaa-1234-1234-1234-123456789abc'),'playing');assert.equal(h.value.pending,2);h.requests[1].resolve(ack());await h.pump();assert.equal(h.value.pending,1);await h.advance(15000);assert.equal(h.requests[2].body.weapons[0].id,'wide');h.unmount();});
await check('Out of order GET cannot lower acknowledged XP',async()=>{const h=await initialized();await h.input(report(),'playing');h.value.retry();await h.pump();assert.equal(h.requests.length,3);h.requests[1].resolve(ack(10));await h.pump();h.requests[2].resolve(ack(0));await h.pump();assert.equal(h.value.xp.precision,10);h.unmount();});
await check('Timed out save remains retryable',async()=>{const h=await initialized();await h.input(report(),'playing');await h.advance(12001);assert.equal(h.value.pending,1);assert.ok(h.value.error);await h.advance(3000);assert.equal(h.requests.length,3);h.unmount();});
await check('Account switch rejects response and preserves old account draft',async()=>{const h=await initialized();await h.input(report(),'playing');h.requests[1].resolve(ack(10,'b'));await h.pump();assert.equal(h.value.pending,1);assert.ok(h.value.error.includes('保存先'));assert.equal(h.value.xp.precision,undefined);h.unmount();});
await check('Missing receipt drains discarded draft without granting XP or retry loop',async()=>{const h=await initialized();await h.input(report(),'result');assert.equal(h.requests[1].body.ownerKey,'a');h.requests[1].resolve({ownerKey:'a',xp:{},receipts:{}});await h.pump();assert.equal(h.value.pending,0);assert.equal(h.value.xp.precision,undefined);assert.equal(h.value.error,'');assert.ok(h.value.notice.includes('未保存または削除済み'));await h.input(report(),'result');await h.advance(16000);assert.equal(h.requests.length,2);h.unmount();});
await check('Mixed owned and discarded reports grant only server acknowledged totals',async()=>{const h=await initialized();const r=report();r.weapons.push({id:'removed',damage:100,kills:1,headshotKills:0});await h.input(r,'result');h.requests[1].resolve({ownerKey:'a',xp:{precision:10},receipts:{precision:10}});await h.pump();assert.equal(h.value.xp.precision,10);assert.equal(h.value.xp.removed,undefined);assert.equal(h.value.pending,0);assert.ok(h.value.notice);h.unmount();});
console.log(n+' client hook checks passed');
