'use client';
import {useEffect,useState} from 'react';
import {Keyboard,RotateCcw} from 'lucide-react';
// @ts-ignore Shared keyboard rules.
import {KEY_ACTIONS,DEFAULT_KEY_BINDINGS,validKeyCode,bindingConflict,keyLabel} from '../engine/controls.js';
export function KeySettings({bindings,onChange,saveError}:{bindings:Record<string,string>,onChange:(b:Record<string,string>)=>void,saveError:string}){
 const [waiting,setWaiting]=useState<string|null>(null),[message,setMessage]=useState('');
 useEffect(()=>{if(!waiting)return;const capture=(e:KeyboardEvent)=>{e.preventDefault();e.stopImmediatePropagation();if(e.repeat||e.isComposing)return;if(e.code==='Escape'){setWaiting(null);setMessage('変更をキャンセルしました。');return;}if(e.metaKey||e.altKey||(e.ctrlKey&&!e.code.startsWith('Control'))||!validKeyCode(e.code)){setMessage('このキーは割り当てできません。別のキーを押してください。');return;}const conflict=bindingConflict(bindings,waiting,e.code);if(conflict){setMessage(`「${conflict.label}」で使用中です。別のキーを押してください。`);return;}onChange({...bindings,[waiting]:e.code});setMessage('キー割り当てを変更しました。');setWaiting(null);};const cancel=()=>{setWaiting(null);};window.addEventListener('keydown',capture,true);window.addEventListener('blur',cancel);return()=>{window.removeEventListener('keydown',capture,true);window.removeEventListener('blur',cancel);};},[waiting,bindings,onChange]);
 return <section className="key-settings" aria-label="キー割り当て設定"><header><div><Keyboard size={20}/><h2>キー割り当て</h2></div><button className="outline-button" onClick={()=>{onChange({...DEFAULT_KEY_BINDINGS});setWaiting(null);setMessage('初期設定に戻しました。');}}><RotateCcw size={15}/> 初期設定に戻す</button></header><p>変更する操作をクリックし、使いたいキーを押してください。このブラウザに自動保存します。Escで変更をキャンセルできます。</p><p className={'key-setting-status '+(saveError?'error':'')} role="status">{saveError||message||(waiting?'キー入力待ち：'+KEY_ACTIONS.find((a:any)=>a.id===waiting)?.label+' · Escでキャンセル':'マウス操作とEscの一時停止は常に利用できます。')}</p><div className="key-setting-groups">{[...new Set(KEY_ACTIONS.map((a:any)=>a.group))].map((group:any)=><fieldset key={group}><legend>{group}</legend>{KEY_ACTIONS.filter((a:any)=>a.group===group).map((a:any)=><div className={'key-setting-row '+(waiting===a.id?'listening':'')} key={a.id}><span>{a.label}</span><button onClick={()=>{setWaiting(waiting===a.id?null:a.id);setMessage('');}} aria-label={`${a.label}のキーを変更、現在${keyLabel(bindings,a.id)}`} aria-pressed={waiting===a.id}>{waiting===a.id?'キーを押す…':keyLabel(bindings,a.id)}</button></div>)}</fieldset>)}</div></section>;
}
export function KeyHelp({bindings,survival}:{bindings:Record<string,string>,survival:boolean}){return <div className="controls-grid">{KEY_ACTIONS.filter((a:any)=>a.mode==='all'||a.mode===(survival?'survival':'conquest')).map((a:any)=><div key={a.id}><kbd>{keyLabel(bindings,a.id)}</kbd><span>{a.label}</span></div>)}<div><kbd>マウス</kbd><span>視点移動</span></div><div><kbd>左クリック</kbd><span>射撃</span></div><div><kbd>右クリック長押し</kbd><span>スコープ</span></div><div><kbd>Esc</kbd><span>一時停止（固定）</span></div></div>;}
