'use client';
import {useEffect,useRef} from 'react';
import {KeyHelp} from './key-settings';
// @ts-ignore Shared key mapping.
import {keyLabel} from '../engine/controls.js';
import {Crosshair,Radio,Shield,Heart,Package,ChevronRight,Map as MapIcon,Pause,Move,ScanLine,ArrowLeft,RotateCcw,Volume2} from 'lucide-react';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
// @ts-ignore Shared survival profiles.
import {SURVIVAL_DIFFICULTIES,getSurvivalDifficulty} from '../engine/survival-rules.js';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
// @ts-ignore Shared engine data.
import {SURVIVAL_MAPS,survivalLayout,survivalTerrain} from '../engine/survival-maps.js';
// @ts-ignore Shared engine statistics.
import {stats,getScope,canPlayDifficulty} from '../engine/model.js';
const time=(n:number)=>`${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`;

export function SurvivalMap({map,hud,large=false}:{map:string,hud?:any,large?:boolean}){
 const ref=useRef<HTMLCanvasElement>(null),base=useRef<HTMLCanvasElement|null>(null);
 useEffect(()=>{const c=document.createElement('canvas');c.width=480;c.height=480;const ctx=c.getContext('2d')!,layout=survivalLayout(map),px=(x:number)=>(x/layout.size+.5)*480,pz=(z:number)=>(z/layout.size+.5)*480;ctx.fillStyle='#233b43';ctx.fillRect(0,0,480,480);
  for(let x=0;x<480;x+=3)for(let z=0;z<480;z+=3){const y=survivalTerrain(map,(x/480-.5)*layout.size,(z/480-.5)*layout.size);ctx.fillStyle=y<0?'#376478':`hsl(${['urban','metro'].includes(map)?35:map==='tidal'?95:137} 12% ${23+y*.43}%)`;ctx.fillRect(x,z,3,3);if(y>0&&y%10<.55){ctx.fillStyle='#b9d0bc2a';ctx.fillRect(x,z,3,3);}}
  ctx.lineWidth=3;ctx.strokeStyle='#c5c6ad90';for(const road of layout.roads){ctx.beginPath();road.forEach(([x,z]:number[],i:number)=>i?ctx.lineTo(px(x),pz(z)):ctx.moveTo(px(x),pz(z)));ctx.stroke();}
  ctx.fillStyle='#d9dbce';for(const b of layout.compounds){ctx.fillRect(px(b.x-b.w/2),pz(b.z-b.d/2),b.w/layout.size*480,b.d/layout.size*480);if(['urban','metro'].includes(map)){ctx.fillStyle='#5e7775';ctx.fillRect(px(b.x-b.w/2)+1,pz(b.z-b.d/2)+1,b.w/layout.size*480-2,b.d/layout.size*480-2);ctx.fillStyle='#d9dbce';}}
  ctx.strokeStyle='#cfdfcf18';ctx.lineWidth=1;for(let p=80;p<480;p+=80){ctx.beginPath();ctx.moveTo(p,0);ctx.lineTo(p,480);ctx.moveTo(0,p);ctx.lineTo(480,p);ctx.stroke();}base.current=c;
 },[map]);
 useEffect(()=>{const c=ref.current,background=base.current;if(!c||!background)return;const ctx=c.getContext('2d')!,w=c.width,l=survivalLayout(map),px=(x:number)=>(x/l.size+.5)*w,pz=(z:number)=>(z/l.size+.5)*w;ctx.clearRect(0,0,w,w);ctx.drawImage(background,0,0,w,w);
  if(hud?.zone){const zone=hud.zone;ctx.fillStyle='#162b4770';ctx.beginPath();ctx.rect(0,0,w,w);ctx.arc(px(zone.x),pz(zone.z),zone.radius/l.size*w,0,Math.PI*2,true);ctx.fill('evenodd');ctx.strokeStyle='#b5ebff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(px(zone.x),pz(zone.z),zone.radius/l.size*w,0,Math.PI*2);ctx.stroke();ctx.setLineDash([5,4]);ctx.strokeStyle='#fff1bf';ctx.beginPath();ctx.arc(px(zone.nextX),pz(zone.nextZ),zone.nextRadius/l.size*w,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}
  for(const [i,p] of l.pois.entries()){ctx.fillStyle='#8ff1d7';ctx.beginPath();ctx.arc(px(p.x),pz(p.z),large?4:3,0,7);ctx.fill();if(large){ctx.font='12px sans-serif';ctx.textAlign='center';ctx.fillStyle='#071a18';ctx.fillRect(px(p.x)-47,pz(p.z)+7,94,19);ctx.fillStyle='#e6f0de';ctx.fillText(`${i+1} ${p.name}`,px(p.x),pz(p.z)+21);}}
  if(hud?.scanning){ctx.fillStyle='#ffb48b';for(const e of hud.enemies||[])if(Math.hypot(e.x-hud.player.x,e.z-hud.player.z)<140){ctx.beginPath();ctx.arc(px(e.x),pz(e.z),3,0,7);ctx.fill();}}
  if(!hud?.player)return;const p=hud.player;ctx.save();ctx.translate(px(p.x),pz(p.z));ctx.rotate(-(hud?.yaw||0));ctx.strokeStyle='#14262b';ctx.lineWidth=2;ctx.fillStyle='#fff4c4';ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(-5,5);ctx.lineTo(0,2);ctx.lineTo(5,5);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();
 },[map,hud,large]);
 return <canvas ref={ref} width={large?480:240} height={large?480:240} aria-label="サバイバル戦場の地形・給電所・安全地帯"/>;
}

export function SurvivalLobby({map,onMap,onStart,ready,error,bindings,difficulty='bachelor',onDifficulty,cleared=[]}:{difficulty?:string,onDifficulty?:(id:string)=>void,cleared?:string[],bindings?:Record<string,string>,map:string,onMap:(id:string)=>void,onStart:()=>void,ready:boolean,error:string}){
 const k=(id:string)=>keyLabel(bindings,id);const profile=getSurvivalDifficulty(difficulty);
 const m=SURVIVAL_MAPS.find((v:any)=>v.id===map)||SURVIVAL_MAPS[0];return <div className="survival-deploy">
  <section className="survival-brief"><div className="survival-kicker"><span/> SURVIVAL / SOLO</div><h1>THE LAST<br/><em>SIGNAL.</em></h1><p className="survival-subtitle">最後まで、電波を絶やすな。</p><div className="survival-facts"><span><strong>51</strong>あなた ＋ AI 50人</span><span><strong>1.04 km</strong>四方の戦場</span></div>
   <p className="survival-description">50人のAIと、あなた。全員が同じアレイで出撃し、現地の部品で武器を構築。給電圏を見極め、最後の1人を目指す。</p>
   <div className="difficulty-selector survival-difficulty"><div className="difficulty-heading"><span>敵AIの強さ</span><small>LEVEL {profile.rank} / 4</small></div><RadioGroup className="difficulty-options" aria-label="サバイバルの敵AI難易度" value={difficulty} onValueChange={id=>{if(canPlayDifficulty(id,cleared))onDifficulty?.(id);}}>{SURVIVAL_DIFFICULTIES.map((d:any)=>{const locked=!canPlayDifficulty(d.id,cleared);return <label key={d.id} className={(difficulty===d.id?'selected ':'')+(locked?'locked ':'')+(d.id==='shirane'?'ultimate':'')}><RadioGroupItem value={d.id} disabled={locked} aria-label={d.label+(locked?'・未解放':'')}/><span>{d.label}</span><small>{locked?'未解放':d.id==='shirane'?'最高難易度':'挑戦可能'}</small></label>;})}</RadioGroup><p>{profile.description}</p><p className="survival-level-rule">白根は拠点制圧の学士・修士・博士を修了すると解放。敵全員に選択した難易度を適用します。</p></div>
   <button className="survival-start" onClick={onStart} disabled={!ready||!!error||!canPlayDifficulty(difficulty,cleared)}><Crosshair size={20}/><span>{error?'3D描画を開始できません':ready?'サバイバルへ出撃':'戦場を準備中…'}</span><ChevronRight/></button><small className="survival-loadout-note">出撃地点は毎試合ランダム。保存済み装備の持ち込みなし。</small>{error&&<div className="survival-engine-error" role="alert"><strong>ブラウザでWebGLを利用できません</strong><p>3D描画に対応したブラウザで開くか、ハードウェアアクセラレーションを有効にして再読み込みしてください。</p><button onClick={()=>location.reload()}>再読み込み</button></div>}
   <div className="survival-rules"><div><Package/><span><b>現地でアレイを構築</b>素子・移相器・給電網・スコープを回収</span></div><div><Radio/><span><b>WPTで生命線を確保</b>救急セルとアーマーセル、各3個まで携帯</span></div><div><ScanLine/><span><b>給電圏が段階的に縮小</b>圏外ではHPが減少。倒されると復活なし</span></div></div>

  </section>
  <section className="survival-theatre"><div className="survival-sector"><span>選択中の戦場</span><strong>{m.name}</strong><p>{m.jp} · {m.weather}</p></div><div className="survival-map-options">{SURVIVAL_MAPS.map((v:any,i:number)=><button key={v.id} className={v.id===map?'selected':''} onClick={()=>onMap(v.id)} aria-pressed={v.id===map}><SurvivalMap map={v.id}/><span className="survival-map-index">0{i+1}</span><div><strong>{v.jp}</strong><small>{v.tag}</small></div></button>)}</div><p className="survival-map-description">{m.desc}</p><p className="survival-map-legend"><i/> WPT給電所 <span>明るい線：道路 / 開始地点は出撃時に決定</span></p><div className="survival-deploy-keys"><span><kbd>{k('pickup')}</kbd> 回収・換装</span><span><kbd>{k('heal')}</kbd> HP回復</span><span><kbd>{k('armor')}</kbd> アーマー</span><span><kbd>{k('map')}</kbd> マップ</span></div></section>
 </div>;
}

function SurvivalTouch({engine}:{engine:any}){const move=useRef<any>(null),look=useRef<any>(null);return <div className="touch-controls survival-touch"><div className="touch-look" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);look.current={x:e.clientX,y:e.clientY};}} onPointerMove={e=>{if(look.current){engine.look((e.clientX-look.current.x)*1.6,(e.clientY-look.current.y)*1.6);look.current={x:e.clientX,y:e.clientY};}}} onPointerUp={()=>look.current=null} onPointerCancel={()=>look.current=null}/><div className="move-pad" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);move.current={x:e.clientX,y:e.clientY};}} onPointerMove={e=>{if(move.current)engine.touchMove={x:Math.max(-1,Math.min(1,(e.clientX-move.current.x)/35)),y:Math.max(-1,Math.min(1,(e.clientY-move.current.y)/35))};}} onPointerUp={()=>{move.current=null;engine.touchMove={x:0,y:0};}} onPointerCancel={()=>{move.current=null;engine.touchMove={x:0,y:0};}}><Move/></div><button className="touch-fire" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);engine.initAudio();engine.fire=true;}} onPointerUp={()=>engine.fire=false} onPointerCancel={()=>engine.fire=false}>FIRE</button><button className="touch-aim" onClick={()=>engine.toggleAim()}>ADS</button><button className="touch-scan" onClick={()=>engine.pickup()}>回収</button><button className="touch-reload" onClick={()=>engine.recharge()} aria-label="エネルギー交換">充電</button><button className="touch-wpt" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);engine.wptHeld=true;}} onPointerUp={()=>engine.wptHeld=false} onPointerCancel={()=>engine.wptHeld=false}>WPT</button><button className="touch-jump" onClick={()=>engine.keys.Space=true}>JUMP</button></div>;}

export function SurvivalHUD({hud,map,engine,onStart,bindings}:{hud:any,map:string,engine:any,onStart:()=>void,bindings?:Record<string,string>}){
 const k=(id:string)=>keyLabel(bindings,id);
 const setup=hud.activeSetup,st=stats(setup),zone=hud.zone||{},loot=hud.loot;return <>
  <div className={'damage-vignette '+(hud.damage?'visible':'')}/><div className={'survival-hud '+(hud.zoneOutside?'outside':'')}>
   <div className="survival-top"><span className="survival-live"><b>{hud.remainingAlive??51}</b><small>生存 / 51 · {getSurvivalDifficulty(hud.difficultyId).label}</small></span><span className="survival-kills"><b>{hud.kills}</b><small>撃破</small></span><div className="survival-zone-clock"><Radio size={17}/><span>{zone.shrinking?'給電圏が縮小中':'次の給電圏まで'}<strong>{time(zone.remaining||0)}</strong></span><small>PHASE {zone.phase||1} / 6</small></div></div>
   <div className="survival-heading">{['N','NE','E','SE','S','SW','W','NW'][((Math.round(-hud.yaw/(Math.PI/4))%8)+8)%8]} <span>{((Math.round(-hud.yaw*180/Math.PI)%360)+360)%360}°</span></div>
   <div className="survival-radar"><button onClick={()=>{engine.mapOpen=!engine.mapOpen;engine.emit();}} aria-label="全体マップを開く"><SurvivalMap map={map} hud={hud}/></button><span><kbd>{k('map')}</kbd> 全体マップ <b>{hud.zoneDistance>0?`次の圏まで ${hud.zoneDistance} m`:'次の給電圏内'}</b></span></div>
   <button className="survival-pause" onClick={()=>engine.pause()} aria-label="一時停止"><Pause size={18}/><span>ESC</span></button>
   <div className="survival-feed">{hud.eliminations?.map((e:any)=><p key={e.id}>{e.text}</p>)}</div>
   {hud.mode==='playing'&&<>{hud.zoneOutside&&<div className="survival-zone-warning"><Radio size={18}/> 給電圏外 · HP減少中 <strong>安全地帯へ移動</strong></div>}{hud.message&&<div className="survival-message" role="status">{hud.message}</div>}
    <div className={'crosshair '+(hud.aiming?'scope-hidden ':'')+(hud.hit?'hit':'')+(hud.overheat?' overheated':'')}><i/><i/><i/><i/><span/></div><div className="beam-aim-markers" aria-hidden="true">{hud.aimMarkers?.map((p:any,i:number)=><span key={i} style={{left:Math.max(6,Math.min(94,p.x))+'%',top:Math.max(14,Math.min(86,p.y))+'%'}}>{p.visible?'◇':''}</span>)}</div>
    {!hud.aiming&&!loot&&hud.lootMarkers?.filter((p:any)=>!p.offscreen).map((p:any)=><div key={p.id} className="survival-loot-marker" style={{left:p.x+'%',top:p.y+'%',color:p.color}}><Package size={18}/><span>{p.distance} m</span></div>)}
    {hud.headshot&&<div className="headshot-notice">HEADSHOT <span>頭部命中 ×1.75</span></div>}{hud.killNotice&&<div className="kill-notice">{hud.killHeadshot?'ヘッドショットで撃破':'生存者を撃破'}</div>}
    {hud.consume?<div className="survival-consume"><Radio/><div><strong>{hud.consume.resource==='heal'?'WPTレクテナ · HP修復':'WPT共振結合 · アーマー充填'}</strong><progress value={hud.consume.elapsed} max={hud.consume.duration}/><small>静止して給電 · 残り {(hud.consume.duration-hud.consume.elapsed).toFixed(1)}秒</small></div></div>:loot?<div className="survival-loot-card" style={{borderColor:loot.color}}><div><Package size={21} style={{color:loot.color}}/><span><small>{loot.kind==='consumable'?'WPT SUPPLY':'PHASED ARRAY MODULE'}</small><strong>{loot.name}</strong></span><kbd>{k('pickup')}</kbd></div><p>{loot.description}</p>{loot.kind==='module'&&<div className="survival-item-compare"><span>射程 <b>{Math.round(loot.before.range)} → {Math.round(loot.after.range)} m</b></span><span>火力 <b>{Math.round(loot.before.dps)} → {Math.round(loot.after.dps)}</b></span><span>移動 <b>{loot.before.moveSpeed.toFixed(1)} → {loot.after.moveSpeed.toFixed(1)} m/s</b></span></div>}<small>{loot.tradeoff}</small><button onClick={()=>engine.pickup()} disabled={!loot.ok}>{loot.ok?(loot.kind==='consumable'?`${k('pickup')} · セルを回収`:`${k('pickup')} · この部品に換装`):loot.reason}</button></div>:hud.wpt?.status!=='inactive'&&<div className="survival-station"><Radio/><span><strong>{hud.wpt?.status==='charging'?'WPT給電中':hud.wpt?.status==='contested'?'給電所で交戦中':hud.wpt?.status==='ready'?`${k('wpt')} 長押しでWPT受電`:hud.wpt?.status==='complete'?'充填済み':'静止して安全を確保'}</strong><small>アーマー +12/s · エネルギー +24/s</small></span></div>}
    {hud.overheat&&<div className="center-notice">OVERHEAT<small>冷却を待って再射撃</small></div>}{hud.reload>0&&<div className="center-notice">RECHARGING<small>{hud.reload.toFixed(1)} s</small></div>}
   </>}
   <div className="survival-bottom"><div className="survival-vitals"><div><Shield size={18}/><span>WPT ARMOR</span><strong>{hud.shield??0}<small>/100</small></strong></div><progress className="armor" value={hud.shield||0} max={100}/><div><Heart size={18}/><span>HEALTH</span><strong>{hud.hp}<small>/100</small></strong></div><progress value={hud.hp} max={100}/><div className="survival-cells"><button onClick={()=>engine.useCell('heal')} disabled={!hud.inventory?.heal}><kbd>{k('heal')}</kbd><Heart size={15}/> 救急 <b>{hud.inventory?.heal||0}/3</b></button><button onClick={()=>engine.useCell('shield')} disabled={!hud.inventory?.shield}><kbd>{k('armor')}</kbd><Shield size={15}/> アーマー <b>{hud.inventory?.shield||0}/3</b></button></div></div>
    <div className="survival-weapon"><span>FIELD ARRAY <small>{getScope(setup.scope).label}</small></span><div><strong>{hud.energy}<small>/100</small></strong><span>{setup.beamCount} BEAM{setup.beamCount>1?'S':''}<small>{setup.elements}素子 · {setup.power}% · {setup.fireRate} Hz</small></span></div><progress value={hud.heat} max={100}/><p>HEAT {hud.heat}% <span>{k('reload')} 再充電 / {st.reloadSeconds.toFixed(1)} s</span></p><small>{k('pickup')} 回収 · {k('wpt')} WPT給電 · {k('autorun')} 自動走行 · {k('aim')} スコープ</small></div></div>
  </div>
  {hud.mapOpen&&hud.mode==='playing'&&<div className="survival-map-panel"><div><span>TACTICAL MAP</span><button onClick={()=>{engine.mapOpen=false;engine.emit();}}>{k('map')} · 閉じる</button></div><SurvivalMap map={map} hud={hud} large/><p>実線：現在の給電圏　破線：次の給電圏　緑：WPT給電所</p><div className="survival-build"><strong>現在のアレイ構成</strong>{[['素子数',setup.elements],['位相分解能',setup.bits+' bit'],['送信出力',setup.power+'%'],['ビーム幅',setup.width+'°'],['ビーム数',setup.beamCount],['分岐角','±'+setup.split+'°'],['電子偏向',setup.steering+'°'],['走査幅','±'+setup.scanWidth+'°'],['パルス',setup.fireRate+' Hz'],['振幅',setup.taper],['冷却配分',setup.cooling+'%'],['スコープ',getScope(setup.scope).label]].map(([label,value])=><span key={label}>{label}<b>{value}</b></span>)}</div></div>}
  {hud.mode==='playing'&&<SurvivalTouch engine={engine}/>}
  <Dialog open={hud.mode==='paused'} onOpenChange={o=>{if(!o)engine.resume();}}><DialogContent className="game-dialog survival-dialog"><div className="eyebrow">SURVIVAL PAUSED</div><DialogTitle>一時停止</DialogTitle><DialogDescription>敵AIと給電圏の時間も停止しています。</DialogDescription><button className="survival-start" onClick={()=>engine.resume()}>戦場に戻る <ChevronRight/></button><KeyHelp bindings={bindings||{}} survival/><button className="outline-button" onClick={()=>engine.menu()}><ArrowLeft size={17}/> 出撃画面に戻る</button></DialogContent></Dialog>
  <Dialog open={hud.mode==='result'}><DialogContent className="game-dialog survival-result" showCloseButton={false} onEscapeKeyDown={e=>e.preventDefault()} onInteractOutside={e=>e.preventDefault()}><div className="eyebrow">SURVIVAL / OPERATION COMPLETE</div><DialogTitle>{hud.result?.outcome==='victory'?'LAST SIGNAL STANDING':hud.result?.outcome==='draw'?'NO SIGNAL REMAINS':'SIGNAL LOST'}</DialogTitle><div className="survival-placement">#{hud.result?.placement||51}<small>/ 51</small></div><DialogDescription>{hud.result?.reason}</DialogDescription><div className="survival-result-stats"><span><b>{hud.kills}</b>撃破</span><span><b>{time(hud.result?.elapsed||0)}</b>生存時間</span><span><b>{hud.headshotKills||0}</b>頭部撃破</span></div><p>回収した部品はこの試合で終了。次の出撃は同じ初期装備から始まります。</p><button className="survival-start" onClick={onStart}><RotateCcw size={18}/> もう一度サバイバルへ</button><button className="outline-button" onClick={()=>engine.menu()}>出撃画面に戻る</button></DialogContent></Dialog>
 </>;
}
